name: mlflow-env
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow>=2.10.0
      - scikit-learn>=1.4.0
      - pandas
      - numpy
      - matplotlib
      - seaborn
      - dagshub